// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 22de5c086a7b05bc "Logitrade", do not edit manually */
"use client";
import {
  stdin_default
} from "../chunks/chunk-2QSAZK3W.js";

// virtual:header/menu-item
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "xkfgwlGWC"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "Etmru3KG0": { "path": "/404" }, "M8YVSMxgJ": { "path": "/book-a-demo" }, "djFcOBxgH": { "path": "/" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "22de5c086a7b05bc94c7df155862c055fe61eda0d80f29da87697e356b6bca4b",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "Etmru3KG0": {
          "path": "/404"
        },
        "M8YVSMxgJ": {
          "path": "/book-a-demo"
        },
        "djFcOBxgH": {
          "path": "/"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "22de5c086a7b05bc94c7df155862c055fe61eda0d80f29da87697e356b6bca4b",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
